library(scales)

returns <- runif(100)
yticks_val <- pretty_breaks(n=10)(returns)

a1 <- scan("./input/high18.txt")
a2 <- matrix(a1,ncol=101,byrow=T)
a3 <- apply(a2[2:19,],2,mean, na.rm=TRUE)
b1 <- scan("./input/low18.txt")
b2 <- matrix(b1,ncol=101,byrow=T)
b3 <- apply(b2[2:19,],2,mean, na.rm=TRUE)
d1 <- scan("./input/tumor.txt")
d2 <- matrix(d1,ncol=101,byrow=T)
d3 <- apply(d2[2:6,],2,mean, na.rm=TRUE)

plot(cbind(b2[1,]/1000,b3),type="p",xlab="HOXB13 location (kb) at Chromosome 17",ylim=c(0,1),ylab="Percentage methylation",col= 'blue', pch = 16, lwd = 3, cex = 1, yaxt="n")
points(cbind(a2[1,]/1000,a3),type="p",col = 'red', pch = 16, lwd = 3, cex = 1)
points(cbind(d2[1,]/1000,d3),type="p",col = 'darkolivegreen', pch = 16, lwd = 3, cex = 1)
legend('topright', c("tumor", "HOXB13 low CRPC", "HOXB13 high CRPC"), lty=1, col=c('darkolivegreen', 'blue', 'red'), bty='n', cex=1, lwd = 3)
pdf(file="./result/tumor_HOXB13high18CRPC_HOXB13low18CRPC_result.pdf",width =7,height = 7)   
